# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.22.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import focs_gitea
from focs_gitea.models.topic_response import TopicResponse  # noqa: E501
from focs_gitea.rest import ApiException


class TestTopicResponse(unittest.TestCase):
    """TopicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTopicResponse(self):
        """Test TopicResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = focs_gitea.models.topic_response.TopicResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
