# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.22.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import find_packages, setup  # noqa: H301

NAME = "focs-gitea"
VERSION = "1.22.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="Python SDK for FOCS Gitea API.",
    author="BoYanZh",
    author_email="bomingzh@sjtu.edu.cn",
    url="https://github.com/BoYanZh/focs-gitea",
    keywords=["Swagger", "Gitea API."],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
)
